language: cpp
os: linux
sudo: required
dist: trusty
compiler: gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y libqt4-dev qt4-qmake libboost-all-dev 
script: ./build.sh
notifications:
    email:
        recipients: aijunbai@gmail.com
        on_success: change
        on_failure: always

